---
name: SQLite-VirtualTable-Pivot
version: 0.01
author:
  - 'Brian Duggan <bduggan@matatu.org>'
abstract: Manipulate pivot tables using sqlite virtual tables
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bduggan/SQLite-VirtualTable-Pivot/tree/master
build_requires:
  Class::Accessor::Contextual: 0
  DBD::SQLite: 1.25
  DBI: 0
  DBIx::Simple: 0
  SQLite::VirtualTable: 0
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  SQLite::VirtualTable::Pivot:
    file: lib/SQLite/VirtualTable/Pivot.pm
    version: 0.01
  SQLite::VirtualTable::Pivot::Cursor:
    file: lib/SQLite/VirtualTable/Pivot/Cursor.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
